## Part 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[0.5, 1],[np.NaN, 2], [0.2,]])

In [3]:
df

0    1
0  0.5  1.0
1  NaN  2.0
2  0.2  NaN

### Questions
* Replace Nan in both columns with
* Zero
* max
* min
* mean
* median

In [4]:
print(df)

     0    1
0  0.5  1.0
1  NaN  2.0
2  0.2  NaN


In [5]:
#Replacing NaN with Zero
print('Replacing NaN with Zero')
dataframe1 = df.fillna(0)
print(dataframe1)
print('-----------------')

#Replacing NaN with Max of column
print('Replacing NaN with Max of column')
dataframe2 = df.apply(lambda y: y.fillna(y.max()),axis=0)
print(dataframe2)
print('-----------------')

#Replacing NaN with Min of column
print('Replacing NaN with Min of column')
dataframe3 = df.apply(lambda y: y.fillna(y.min()),axis=0)
print(dataframe3)
print('-----------------')

#Replacing NaN with Mean of column
print('Replacing NaN with Mean of column')
dataframe4 = df.apply(lambda y: y.fillna(y.mean()),axis=0)
print(dataframe4)
print('-----------------')

#Replacing NaN with Median of column
print('Replacing NaN with Median of column')
dataframe5 = df.apply(lambda y: y.fillna(y.median()),axis=0)
print(dataframe5)
print('-----------------')

Replacing NaN with Zero
     0    1
0  0.5  1.0
1  0.0  2.0
2  0.2  0.0
-----------------
Replacing NaN with Max of column
     0    1
0  0.5  1.0
1  0.5  2.0
2  0.2  2.0
-----------------
Replacing NaN with Min of column
     0    1
0  0.5  1.0
1  0.2  2.0
2  0.2  1.0
-----------------
Replacing NaN with Mean of column
      0    1
0  0.50  1.0
1  0.35  2.0
2  0.20  1.5
-----------------
Replacing NaN with Median of column
      0    1
0  0.50  1.0
1  0.35  2.0
2  0.20  1.5
-----------------


## Part 2

Using breast cancer dataset available in sklearn, train & test accuracy of your result using SVM.  You can use any library for the computation but a detailed explanation of it's parameters should be provided along with your reason to use them.

In [6]:
from sklearn.datasets import load_breast_cancer

In [7]:
#Loading breast cancer data set 
data = load_breast_cancer()

In [8]:
print(data.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [9]:
print(data.target_names)

['malignant' 'benign']


In [10]:
print(data.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [11]:
x=data.data
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [12]:
y=data.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [13]:
#Splitting data into training and testing dataset
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [14]:
#Building an SVM model 
from sklearn import svm

classifier = svm.SVC()
classifier.fit(x_train,y_train)

/Users/shalabhneema/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [15]:
#Calculating accuracy of this model (how it performs)
from sklearn import metrics

y_pred = classifier.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print(accuracy)

0.5847953216374269


Changing the kernal from poly to Linier

In [16]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print(accuracy)

0.9649122807017544


Here we can see that there is a drastic change in the accuracy when we shift the kernal from poly to Linear. It means that classification are linearly seperable.Now lets check if the outlier values would have an affect on accuracy. We will try to change the gamma and C values while keeping the kernal as Linier


In [17]:
classifier = svm.SVC(kernel='linear',C=2)
classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print(accuracy)

0.9707602339181286


Here we can see that accuracy has been increased  it means when we give model freedom to include more samples it performs well

Lets try to change the gamma values now and see if there is any impact.

In [18]:
classifier = svm.SVC(kernel='linear',C=2,gamma=3)
classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print(accuracy)

0.9707602339181286


So no change in accuracy as we change the gamma.